# Generated by Django 4.1.6 on 2024-03-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_contest_allow_only_python'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='submission_size_limit_in_bytes',
            field=models.IntegerField(default=200000),
        ),
    ]
