# Generated by Django 4.2.24 on 2025-09-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_problem_submission_size_limit_in_bytes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='allow_only_python',
            new_name='only_allow_python',
        ),
        migrations.AddField(
            model_name='contest',
            name='only_practice_contest',
            field=models.BooleanField(default=False),
        ),
    ]
