# Generated by Django 5.2 on 2026-09-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_rename_allow_only_python_contest_only_allow_python_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='count_shots',
            field=models.BooleanField(default=False),
        ),
    ]
