---
- name: Install nginx
  hosts: web
  remote_user: root

  tasks:
  - name: Ensure nginx is at the latest version
    ansible.builtin.apt:
      update_cache: yes
      name: nginx
      state: latest

- name: Install omogenjudge-web
  hosts: web

  tasks:
  - name: Upload deb
    ansible.builtin.copy:
      src: ./packages/omogenjudge-web.deb
      dest: omogenjudge-web.deb

  - name: Install omogenjudge-web.deb
    ansible.builtin.command: dpkg -i omogenjudge-web.deb
